### ISSUE TITLE
mount: block device none is write-protected, mounting read-only

### ISSUE THREAD

**Issue by joshuataylor** [gentics/docker-tmpfs-mysql#3]
Getting this on my local machine, works fine on another.

Ubuntu 15.04, works fine on 14.04, not sure if it's the version difference or something else.

**Comment by joshuataylor** [comment]
Using --privileged is a workaround for this.

**Comment by Jotschi** [comment]
I deprecated this project in favour of the official way to setup mysql via docker tmpfs. See updated readme for details.
